services:
  - type: web
    name: grinsamanufacturas-frontend
    env: static
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: grinsamanufacturas-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js

    routes:
      - type: proxy
        source: /api/*
        destination: https://grinsamanufacturasbackend.onrender.com
