version: 1
services:
  - type: web
    name: my-react-node-app
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: frontend/build
    headers:
      - source: '**'
        headers:
          - key: Cache-Control
            value: max-age=0
    redirects:
      - source: '/*'
        destination: '/'
        status: 200
